<section class="legal-hero" style="--legal-bg: url('<?= h(asset_url('backgrounds/10.png')) ?>')">
    <div class="container"><div class="breadcrumbs breadcrumbs-light"><a href="<?= h(page_url()) ?>">Home</a><span>/</span><span>Privacy & Policies</span></div><span class="eyebrow eyebrow-light">Transparency. Trust. Commitment.</span><h1>Privacy Policy &<br>Non-Refund Policy</h1><p>Your trust is our first priority. We protect your information and explain our digital-service terms clearly.</p></div>
</section>
<section class="section legal-content">
    <div class="container legal-columns">
        <article class="legal-card reveal"><div class="legal-card-title"><?= icon('shield') ?><div><span>Privacy Policy</span><h2>Effective from August 2026</h2></div></div><p>Smart Global Group respects your privacy and handles personal information responsibly, transparently, and only for legitimate business purposes.</p><h3>1. Information We Collect</h3><p>We may collect identity, contact, company, service-interest, payment, device, and correspondence information that you provide directly or generate when using our website.</p><h3>2. How We Use Your Information</h3><p>We use information to respond to requests, provide contracted services, process payments, improve our offers, meet legal obligations, and send communications where you have consented.</p><h3>3. Data Sharing</h3><p>We do not sell personal data. Information may be shared with vetted service providers, professional advisors, regulators, or delivery partners only when necessary and subject to appropriate safeguards.</p><h3>4. Security & Retention</h3><p>We apply reasonable technical and organizational controls and retain information only as long as required for the purpose collected or by applicable law.</p><h3>5. Your Rights</h3><p>You may request access, correction, deletion, restriction, or withdrawal of consent, subject to legal and contractual requirements. Contact our privacy team at info@smartglobalgroup.com.</p></article>

        <article class="legal-card legal-card-gold reveal"><div class="legal-card-title"><?= icon('briefcase') ?><div><span>Digital Solutions</span><h2>Cancellation & Non-Refund Policy</h2></div></div><p>Digital projects involve reserved expert time, third-party services, and progressive delivery. The following policy supports clear expectations for every engagement.</p><h3>Before Work Starts</h3><p>Cancellation requests submitted before the agreed start date may be eligible for a partial refund, less assessment, administration, payment-processing, and third-party costs already incurred.</p><h3>After Work Commences</h3><p>Payments become non-refundable once discovery, design, development, licensing, procurement, configuration, consultation, or any other agreed work has started.</p><h3>Milestones & Change Requests</h3><p>Approved milestones are deemed accepted according to the project agreement. Work outside the agreed scope requires a written change request and may affect fees and delivery dates.</p><h3>Client Responsibilities</h3><p>The client must provide accurate information, access, approvals, and feedback on time. Delays caused by missing client inputs do not create a right to a refund.</p><h3>Service Quality</h3><p>If an agreed deliverable materially differs from the written scope, Smart Global will first receive a reasonable opportunity to correct it.</p></article>
    </div>
    <div class="container legal-assurance reveal"><span><?= icon('shield') ?><b>Your secure data</b></span><span><?= icon('users') ?><b>Transparent policies</b></span><span><?= icon('globe') ?><b>Client rights respected</b></span><span><?= icon('check') ?><b>Global compliance</b></span></div>
</section>
